version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: smartcart_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:5.7.29
    container_name: smartcart_mysql
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartcart_dev
      MYSQL_USER: smartcart_user
      MYSQL_PASSWORD: smart123

  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: smartcart_php
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
